name: Pong

on:
  workflow_dispatch:
  schedule:
    - cron:  "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      
      - run: cd src && npm install && npm start
